return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "comment",
        "css",
        "dockerfile",
        "go",
        "gomod",
        "graphql",
        "hcl",
        "hocon",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "pug",
        "python",
        "query",
        "regex",
        "scala",
        "scss",
        "swift",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      },
      context_commentstring = {
        enable = true,
      },
      autotag = {
        enable = true,
      },
    },
  },
}
